config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "customers#index"
  resources :customers do
    collection do
      get :alphabetized
      get :missing_email
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, presence: true
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.all.order(:full_name)
  end

  def missing_email
    @customers = Customer.select { |c| c.email_address.blank? }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="card text-white bg-secondary mb-3" style="width: 18rem; margin: 0px 10px 10px 0px;">
  <div class="card-body" style="height: 460px;">
    <h2>Anh Tran</h2>
    <%=image_tag(customer.image, class: "card-img-top", style: "width: auto; max-height: 190px;") rescue nil%>
    <p><%=customer.notes%></p>
    <p><%=customer.phone_number%></p>
    <p><%=customer.email_address%></p>
  </div>
</div>

app/views/customers/alphabetized.html.erb
<div class="container">
  <h1> Alphabetical </h1>
  <div class="row">
    <% @customers.each do |customer| %>
      <div class="column">
        <%= render partial: "customer", locals: { customer: customer } %>
      </div>
    <% end %>
  </div>
  <%= link_to "Home Page", root_path %>
</div>

app/views/customers/index.html.erb
<div class="container">
  <h1> Home Page </h1>
  <div class="row">
    <% @customers.each do |customer| %>
      <div class="column">
        <%= render partial: "customer", locals: { customer: customer } %>
      </div>
    <% end %>
  </div>

<%= link_to "Missing Email", missing_email_customers_path %>
<br>
<%= link_to "Alphabetized", alphabetized_customers_path %>
</div>

app/views/customers/missing_email.html.erb
<div class="container">
  <h1> Missing Email </h1>
  <div class="row">
    <% @customers.each do |customer| %>
      <div class="column">
        <%= render partial: "customer", locals: { customer: customer } %>
      </div>
    <% end %>
  </div>
  <%= link_to "Home Page", root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>